import type { User, Lead, Anotacao, HistoricoMovimentacao } from '@/types'

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    nome: 'Joao Silva',
    email: 'admin@correpool.com',
    tipo: 'admin',
  },
  {
    id: 'u2',
    nome: 'Carlos Mendez',
    email: 'carlos@correpool.com',
    tipo: 'vendedor',
  },
  {
    id: 'u3',
    nome: 'Ana Souza',
    email: 'ana@correpool.com',
    tipo: 'vendedor',
  },
  {
    id: 'u4',
    nome: 'Pedro Lima',
    email: 'pedro@correpool.com',
    tipo: 'sdr',
    vendedorVinculado: 'u2',
  },
  {
    id: 'u5',
    nome: 'Mariana Costa',
    email: 'mariana@correpool.com',
    tipo: 'sdr',
    vendedorVinculado: 'u3',
  },
]

export const MOCK_LEADS: Lead[] = [
  // --- FECHADOS ---
  {
    id: 'l1',
    nome: 'Rafael Torres',
    telefone: '(11) 99234-5678',
    email: 'rafael.torres@email.com',
    observacao: 'Muito interessado no plano anual. Tomador de decisao.',
    data_criacao: '2024-03-01',
    data_reuniao: '2024-03-05',
    hora_reuniao: '10:00',
    link_meet: 'https://meet.google.com/abc-defg-hij',
    reuniao_agendada: true,
    temperatura: 'muito_quente',
    status_funil: 'fechado',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'video_depoimento_cliente',
    utm_anuncio: 'AD-VDC-001',
    utm_posicionamento: 'feed',
    valor_contrato: 4800,
  },
  {
    id: 'l2',
    nome: 'Beatriz Nunes',
    telefone: '(21) 98765-4321',
    email: 'beatriz.nunes@empresa.com',
    observacao: 'Diretora de marketing. Conhece bem o produto.',
    data_criacao: '2024-03-03',
    data_reuniao: '2024-03-08',
    hora_reuniao: '14:00',
    link_meet: 'https://meet.google.com/xyz-uvwx-yz1',
    reuniao_agendada: true,
    temperatura: 'muito_quente',
    status_funil: 'fechado',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'video_depoimento_cliente',
    utm_anuncio: 'AD-VDC-002',
    utm_posicionamento: 'stories',
    valor_contrato: 7200,
  },
  {
    id: 'l3',
    nome: 'Henrique Alves',
    telefone: '(31) 97654-3210',
    email: 'henrique@consultoria.com',
    observacao: 'CEO de consultoria. Quer solucao completa.',
    data_criacao: '2024-03-05',
    data_reuniao: '2024-03-10',
    hora_reuniao: '09:00',
    link_meet: 'https://meet.google.com/pqr-stuv-wx2',
    reuniao_agendada: true,
    temperatura: 'muito_quente',
    status_funil: 'fechado',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'google',
    utm_medium: 'cpc',
    utm_campaign: 'search_marca_q1',
    utm_content: 'carrossel_beneficios',
    utm_anuncio: 'AD-CB-001',
    utm_posicionamento: 'pesquisa',
    valor_contrato: 9600,
  },
  {
    id: 'l4',
    nome: 'Fernanda Gomes',
    telefone: '(41) 96543-2109',
    email: 'fernanda@startup.io',
    observacao: 'Startup em crescimento. Orçamento aprovado.',
    data_criacao: '2024-03-07',
    data_reuniao: '2024-03-12',
    hora_reuniao: '15:30',
    link_meet: 'https://meet.google.com/lmn-opqr-st3',
    reuniao_agendada: true,
    temperatura: 'muito_quente',
    status_funil: 'fechado',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'instagram',
    utm_medium: 'social',
    utm_campaign: 'remarketing_q1',
    utm_content: 'video_resultado_antes_depois',
    utm_anuncio: 'AD-VRAD-001',
    utm_posicionamento: 'reels',
    valor_contrato: 3600,
  },
  {
    id: 'l5',
    nome: 'Diego Carvalho',
    telefone: '(51) 95432-1098',
    email: 'diego.carvalho@agencia.com',
    observacao: 'Agencia de publicidade. 5 usuarios.',
    data_criacao: '2024-03-10',
    data_reuniao: '2024-03-15',
    hora_reuniao: '11:00',
    link_meet: 'https://meet.google.com/efg-hijk-lm4',
    reuniao_agendada: true,
    temperatura: 'muito_quente',
    status_funil: 'fechado',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'youtube',
    utm_medium: 'video',
    utm_campaign: 'brand_awareness_q1',
    utm_content: 'video_resultado_antes_depois',
    utm_anuncio: 'AD-VRAD-002',
    utm_posicionamento: 'pre_roll',
    valor_contrato: 12000,
  },
  {
    id: 'l6',
    nome: 'Patricia Rocha',
    telefone: '(61) 94321-0987',
    email: 'patricia@tech.com',
    observacao: 'Empresa de tecnologia. Plano enterprise.',
    data_criacao: '2024-03-12',
    data_reuniao: '2024-03-18',
    hora_reuniao: '16:00',
    reuniao_agendada: true,
    temperatura: 'muito_quente',
    status_funil: 'fechado',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'carrossel_beneficios',
    utm_anuncio: 'AD-CB-002',
    utm_posicionamento: 'feed',
    valor_contrato: 18000,
  },
  // --- CONTRATO ASSINADO ---
  {
    id: 'l7',
    nome: 'Rodrigo Matos',
    telefone: '(71) 93210-9876',
    email: 'rodrigo.matos@negocios.com',
    observacao: 'Assinou contrato ontem. Aguardando pagamento.',
    data_criacao: '2024-03-15',
    data_reuniao: '2024-03-20',
    hora_reuniao: '10:30',
    reuniao_agendada: true,
    temperatura: 'muito_quente',
    status_funil: 'contrato_assinado',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'video_depoimento_cliente',
    utm_anuncio: 'AD-VDC-003',
    utm_posicionamento: 'feed',
    valor_contrato: 6000,
  },
  {
    id: 'l8',
    nome: 'Camila Ferreira',
    telefone: '(81) 92109-8765',
    email: 'camila@varejo.com',
    observacao: 'Contrato enviado e assinado. Muito animada.',
    data_criacao: '2024-03-16',
    data_reuniao: '2024-03-21',
    hora_reuniao: '14:30',
    reuniao_agendada: true,
    temperatura: 'muito_quente',
    status_funil: 'contrato_assinado',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'instagram',
    utm_medium: 'social',
    utm_campaign: 'remarketing_q1',
    utm_content: 'reels_duvidas_frequentes',
    utm_anuncio: 'AD-RDF-001',
    utm_posicionamento: 'reels',
    valor_contrato: 4200,
  },
  // --- CONTRATO ENVIADO ---
  {
    id: 'l9',
    nome: 'Lucas Barbosa',
    telefone: '(91) 91098-7654',
    email: 'lucas@industria.com',
    observacao: 'Contrato enviado. Prazo de analise: 3 dias.',
    data_criacao: '2024-03-18',
    data_reuniao: '2024-03-23',
    hora_reuniao: '09:30',
    reuniao_agendada: true,
    temperatura: 'quente',
    status_funil: 'contrato_enviado',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'google',
    utm_medium: 'cpc',
    utm_campaign: 'search_marca_q1',
    utm_content: 'carrossel_beneficios',
    utm_anuncio: 'AD-CB-003',
    utm_posicionamento: 'pesquisa',
    valor_contrato: 7800,
  },
  {
    id: 'l10',
    nome: 'Isabela Monteiro',
    telefone: '(11) 90987-6543',
    email: 'isabela@educacao.com',
    observacao: 'EdTech em expansao. Proposta de R$ 5k enviada.',
    data_criacao: '2024-03-19',
    data_reuniao: '2024-03-24',
    hora_reuniao: '11:30',
    reuniao_agendada: true,
    temperatura: 'quente',
    status_funil: 'contrato_enviado',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'video_depoimento_cliente',
    utm_anuncio: 'AD-VDC-004',
    utm_posicionamento: 'stories',
    valor_contrato: 5000,
  },
  // --- REUNIAO REALIZADA ---
  {
    id: 'l11',
    nome: 'Thiago Nascimento',
    telefone: '(21) 89876-5432',
    email: 'thiago@saude.com',
    observacao: 'Reuniao muito boa. Disse que vai falar com socio.',
    data_criacao: '2024-03-20',
    data_reuniao: '2024-03-25',
    hora_reuniao: '10:00',
    reuniao_agendada: true,
    temperatura: 'quente',
    status_funil: 'reuniao_realizada',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'instagram',
    utm_medium: 'social',
    utm_campaign: 'remarketing_q1',
    utm_content: 'video_resultado_antes_depois',
    utm_anuncio: 'AD-VRAD-003',
    utm_posicionamento: 'stories',
    valor_contrato: 6600,
  },
  {
    id: 'l12',
    nome: 'Amanda Vieira',
    telefone: '(31) 88765-4321',
    email: 'amanda@comercio.com',
    observacao: 'Dono de loja fisica + ecommerce. Interessado.',
    data_criacao: '2024-03-21',
    data_reuniao: '2024-03-26',
    hora_reuniao: '15:00',
    reuniao_agendada: true,
    temperatura: 'morno',
    status_funil: 'reuniao_realizada',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'banner_desconto_30',
    utm_anuncio: 'AD-BD30-001',
    utm_posicionamento: 'feed',
    valor_contrato: 2400,
  },
  {
    id: 'l13',
    nome: 'Gabriel Santos',
    telefone: '(41) 87654-3210',
    email: 'gabriel@servicos.com',
    observacao: 'Empresa de servicos. Reuniao feita mas ficou em duvida sobre preco.',
    data_criacao: '2024-03-22',
    data_reuniao: '2024-03-27',
    hora_reuniao: '16:30',
    reuniao_agendada: true,
    temperatura: 'morno',
    status_funil: 'reuniao_realizada',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'google',
    utm_medium: 'cpc',
    utm_campaign: 'search_marca_q1',
    utm_content: 'carrossel_beneficios',
    utm_anuncio: 'AD-CB-004',
    utm_posicionamento: 'pesquisa',
  },
  // --- AGENDADOS ---
  {
    id: 'l14',
    nome: 'Leticia Campos',
    telefone: '(51) 86543-2109',
    email: 'leticia@financas.com',
    observacao: 'CFO. Reuniao marcada para amanha.',
    data_criacao: '2024-03-25',
    data_reuniao: '2024-04-01',
    hora_reuniao: '09:00',
    link_meet: 'https://meet.google.com/abc-1234-def',
    reuniao_agendada: true,
    temperatura: 'quente',
    status_funil: 'agendado',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'video_depoimento_cliente',
    utm_anuncio: 'AD-VDC-005',
    utm_posicionamento: 'feed',
  },
  {
    id: 'l15',
    nome: 'Bruno Oliveira',
    telefone: '(61) 85432-1098',
    email: 'bruno.oliveira@logistica.com',
    observacao: 'Empresa de logistica. Quer automatizar funil de vendas.',
    data_criacao: '2024-03-26',
    data_reuniao: '2024-04-02',
    hora_reuniao: '11:00',
    link_meet: 'https://meet.google.com/ghi-5678-jkl',
    reuniao_agendada: true,
    temperatura: 'quente',
    status_funil: 'agendado',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'youtube',
    utm_medium: 'video',
    utm_campaign: 'brand_awareness_q1',
    utm_content: 'video_resultado_antes_depois',
    utm_anuncio: 'AD-VRAD-004',
    utm_posicionamento: 'in_stream',
  },
  {
    id: 'l16',
    nome: 'Vanessa Ramos',
    telefone: '(71) 84321-0987',
    email: 'vanessa@imobiliaria.com',
    observacao: 'Imobiliaria com 20 corretores. Alto potencial.',
    data_criacao: '2024-03-27',
    data_reuniao: '2024-04-03',
    hora_reuniao: '14:00',
    link_meet: 'https://meet.google.com/mno-9012-pqr',
    reuniao_agendada: true,
    temperatura: 'muito_quente',
    status_funil: 'agendado',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'instagram',
    utm_medium: 'social',
    utm_campaign: 'remarketing_q1',
    utm_content: 'reels_duvidas_frequentes',
    utm_anuncio: 'AD-RDF-002',
    utm_posicionamento: 'reels',
  },
  {
    id: 'l17',
    nome: 'Eduardo Pinto',
    telefone: '(81) 83210-9876',
    email: 'eduardo@juridico.com',
    observacao: 'Escritorio de advocacia. Reuniao confirmada.',
    data_criacao: '2024-03-28',
    data_reuniao: '2024-04-04',
    hora_reuniao: '10:30',
    link_meet: 'https://meet.google.com/stu-3456-vwx',
    reuniao_agendada: true,
    temperatura: 'morno',
    status_funil: 'agendado',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'banner_desconto_30',
    utm_anuncio: 'AD-BD30-002',
    utm_posicionamento: 'feed',
  },
  // --- FOLLOWUP 3 ---
  {
    id: 'l18',
    nome: 'Juliana Pereira',
    telefone: '(91) 82109-8765',
    email: 'juliana@moda.com',
    observacao: 'Loja de moda. Sem resposta ha 4 dias.',
    data_criacao: '2024-03-20',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'followup3',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'instagram',
    utm_medium: 'social',
    utm_campaign: 'remarketing_q1',
    utm_content: 'banner_desconto_30',
    utm_anuncio: 'AD-BD30-003',
    utm_posicionamento: 'feed',
  },
  {
    id: 'l19',
    nome: 'Marcos Dias',
    telefone: '(11) 81098-7654',
    email: 'marcos.dias@construcao.com',
    observacao: 'Construtora. Pediu para ligar na proxima semana.',
    data_criacao: '2024-03-21',
    reuniao_agendada: false,
    temperatura: 'morno',
    status_funil: 'followup3',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'google',
    utm_medium: 'cpc',
    utm_campaign: 'search_marca_q1',
    utm_content: 'carrossel_beneficios',
    utm_anuncio: 'AD-CB-005',
    utm_posicionamento: 'pesquisa',
  },
  {
    id: 'l20',
    nome: 'Carolina Lima',
    telefone: '(21) 80987-6543',
    email: 'carolina@alimentacao.com',
    observacao: 'Rede de restaurantes. Interessada mas nao tem urgencia.',
    data_criacao: '2024-03-22',
    reuniao_agendada: false,
    temperatura: 'morno',
    status_funil: 'followup3',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'video_depoimento_cliente',
    utm_anuncio: 'AD-VDC-006',
    utm_posicionamento: 'stories',
  },
  // --- FOLLOWUP 2 ---
  {
    id: 'l21',
    nome: 'Felipe Azevedo',
    telefone: '(31) 79876-5432',
    email: 'felipe@pet.com',
    observacao: 'Petshop com 3 unidades. Segundo followup enviado.',
    data_criacao: '2024-03-24',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'followup2',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'instagram',
    utm_medium: 'social',
    utm_campaign: 'remarketing_q1',
    utm_content: 'banner_desconto_30',
    utm_anuncio: 'AD-BD30-004',
    utm_posicionamento: 'stories',
  },
  {
    id: 'l22',
    nome: 'Renata Silveira',
    telefone: '(41) 78765-4321',
    email: 'renata@clinica.com',
    observacao: 'Clinica medica. Respondeu mas esta avaliando outros.',
    data_criacao: '2024-03-25',
    reuniao_agendada: false,
    temperatura: 'morno',
    status_funil: 'followup2',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'reels_duvidas_frequentes',
    utm_anuncio: 'AD-RDF-003',
    utm_posicionamento: 'feed',
  },
  {
    id: 'l23',
    nome: 'Gustavo Moreira',
    telefone: '(51) 77654-3210',
    email: 'gustavo@auto.com',
    observacao: 'Concessionaria. Pediu apresentacao por email.',
    data_criacao: '2024-03-26',
    reuniao_agendada: false,
    temperatura: 'morno',
    status_funil: 'followup2',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'youtube',
    utm_medium: 'video',
    utm_campaign: 'brand_awareness_q1',
    utm_content: 'video_resultado_antes_depois',
    utm_anuncio: 'AD-VRAD-005',
    utm_posicionamento: 'pre_roll',
  },
  // --- FOLLOWUP 1 ---
  {
    id: 'l24',
    nome: 'Tatiana Freitas',
    telefone: '(61) 76543-2109',
    email: 'tatiana@energia.com',
    observacao: 'Empresa de energia solar. Abriu a mensagem mas nao respondeu.',
    data_criacao: '2024-03-27',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'followup1',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'banner_desconto_30',
    utm_anuncio: 'AD-BD30-005',
    utm_posicionamento: 'feed',
  },
  {
    id: 'l25',
    nome: 'Andre Cavalcante',
    telefone: '(71) 75432-1098',
    email: 'andre@farmacia.com',
    observacao: 'Rede de farmacias. Primeiro followup enviado hoje.',
    data_criacao: '2024-03-28',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'followup1',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'instagram',
    utm_medium: 'social',
    utm_campaign: 'remarketing_q1',
    utm_content: 'reels_duvidas_frequentes',
    utm_anuncio: 'AD-RDF-004',
    utm_posicionamento: 'explore',
  },
  {
    id: 'l26',
    nome: 'Priscila Ribeiro',
    telefone: '(81) 74321-0987',
    email: 'priscila@escola.com',
    observacao: 'Escola particular. Respondeu com interesse.',
    data_criacao: '2024-03-28',
    reuniao_agendada: false,
    temperatura: 'morno',
    status_funil: 'followup1',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'google',
    utm_medium: 'cpc',
    utm_campaign: 'search_marca_q1',
    utm_content: 'carrossel_beneficios',
    utm_anuncio: 'AD-CB-006',
    utm_posicionamento: 'pesquisa',
  },
  // --- PRIMEIRO CONTATO ---
  {
    id: 'l27',
    nome: 'Vitor Mendes',
    telefone: '(91) 73210-9876',
    email: 'vitor@hotel.com',
    observacao: 'Rede hoteleira. Primeiro contato feito via WhatsApp.',
    data_criacao: '2024-03-29',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'primeiro_contato',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'banner_desconto_30',
    utm_anuncio: 'AD-BD30-006',
    utm_posicionamento: 'stories',
  },
  {
    id: 'l28',
    nome: 'Simone Tavares',
    telefone: '(11) 72109-8765',
    email: 'simone@advocacia.com',
    observacao: 'Escritorio juridico. Aguardando retorno.',
    data_criacao: '2024-03-29',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'primeiro_contato',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'instagram',
    utm_medium: 'social',
    utm_campaign: 'remarketing_q1',
    utm_content: 'video_depoimento_cliente',
    utm_anuncio: 'AD-VDC-007',
    utm_posicionamento: 'feed',
  },
  {
    id: 'l29',
    nome: 'Rodrigo Farias',
    telefone: '(21) 71098-7654',
    email: 'rodrigo.farias@academia.com',
    observacao: 'Academia com 3 unidades. Muito receptivo.',
    data_criacao: '2024-03-30',
    reuniao_agendada: false,
    temperatura: 'morno',
    status_funil: 'primeiro_contato',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'youtube',
    utm_medium: 'video',
    utm_campaign: 'brand_awareness_q1',
    utm_content: 'video_resultado_antes_depois',
    utm_anuncio: 'AD-VRAD-006',
    utm_posicionamento: 'bumper',
  },
  {
    id: 'l30',
    nome: 'Natalia Costa',
    telefone: '(31) 70987-6543',
    email: 'natalia@beleza.com',
    observacao: 'Rede de saloes. Primeiro contato feito. Retorno pendente.',
    data_criacao: '2024-03-30',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'primeiro_contato',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'banner_desconto_30',
    utm_anuncio: 'AD-BD30-007',
    utm_posicionamento: 'feed',
  },
  // --- TRAFEGO PAGO (novos) ---
  {
    id: 'l31',
    nome: 'Alexandre Borges',
    telefone: '(41) 69876-5432',
    email: 'alexandre@seg.com',
    observacao: '',
    data_criacao: '2024-04-01',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'trafego_pago',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'video_depoimento_cliente',
    utm_anuncio: 'AD-VDC-008',
    utm_posicionamento: 'feed',
  },
  {
    id: 'l32',
    nome: 'Monica Leal',
    telefone: '(51) 68765-4321',
    email: 'monica@rh.com',
    observacao: '',
    data_criacao: '2024-04-01',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'trafego_pago',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'instagram',
    utm_medium: 'social',
    utm_campaign: 'remarketing_q1',
    utm_content: 'carrossel_beneficios',
    utm_anuncio: 'AD-CB-007',
    utm_posicionamento: 'explore',
  },
  {
    id: 'l33',
    nome: 'Cristiano Prado',
    telefone: '(61) 67654-3210',
    email: 'cristiano@infra.com',
    observacao: '',
    data_criacao: '2024-04-02',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'trafego_pago',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'banner_desconto_30',
    utm_anuncio: 'AD-BD30-008',
    utm_posicionamento: 'stories',
  },
  {
    id: 'l34',
    nome: 'Eliane Santos',
    telefone: '(71) 66543-2109',
    email: 'eliane@consultoria.com',
    observacao: '',
    data_criacao: '2024-04-02',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'trafego_pago',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'google',
    utm_medium: 'cpc',
    utm_campaign: 'search_marca_q1',
    utm_content: 'video_depoimento_cliente',
    utm_anuncio: 'AD-VDC-009',
    utm_posicionamento: 'pesquisa',
  },
  {
    id: 'l35',
    nome: 'Marcelo Vianna',
    telefone: '(81) 65432-1098',
    email: 'marcelo@contabil.com',
    observacao: '',
    data_criacao: '2024-04-03',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'trafego_pago',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'youtube',
    utm_medium: 'video',
    utm_campaign: 'brand_awareness_q1',
    utm_content: 'video_resultado_antes_depois',
    utm_anuncio: 'AD-VRAD-007',
    utm_posicionamento: 'pre_roll',
  },
  {
    id: 'l36',
    nome: 'Debora Assis',
    telefone: '(91) 64321-0987',
    email: 'debora@mktdigital.com',
    observacao: '',
    data_criacao: '2024-04-03',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'trafego_pago',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'instagram',
    utm_medium: 'social',
    utm_campaign: 'remarketing_q1',
    utm_content: 'reels_duvidas_frequentes',
    utm_anuncio: 'AD-RDF-005',
    utm_posicionamento: 'reels',
  },
  {
    id: 'l37',
    nome: 'Leonardo Castro',
    telefone: '(11) 63210-9876',
    email: 'leonardo@imoveis.com',
    observacao: '',
    data_criacao: '2024-04-04',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'trafego_pago',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'banner_desconto_30',
    utm_anuncio: 'AD-BD30-009',
    utm_posicionamento: 'feed',
  },
  {
    id: 'l38',
    nome: 'Sandra Moura',
    telefone: '(21) 62109-8765',
    email: 'sandra@saas.com',
    observacao: '',
    data_criacao: '2024-04-04',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'trafego_pago',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'google',
    utm_medium: 'cpc',
    utm_campaign: 'search_marca_q1',
    utm_content: 'carrossel_beneficios',
    utm_anuncio: 'AD-CB-008',
    utm_posicionamento: 'pesquisa',
  },
  // --- DECLINADOS ---
  {
    id: 'l39',
    nome: 'Sergio Lopes',
    telefone: '(31) 61098-7654',
    email: 'sergio@papelaria.com',
    observacao: 'Nao tem orcamento agora. Voltar em 6 meses.',
    data_criacao: '2024-02-15',
    reuniao_agendada: false,
    temperatura: 'desqualificado',
    status_funil: 'declinado',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'banner_desconto_30',
    utm_anuncio: 'AD-BD30-010',
    utm_posicionamento: 'feed',
  },
  {
    id: 'l40',
    nome: 'Aline Queiroz',
    telefone: '(41) 60987-6543',
    email: 'aline@grafica.com',
    observacao: 'Fechou com concorrente. Preco mais baixo.',
    data_criacao: '2024-02-18',
    reuniao_agendada: false,
    temperatura: 'desqualificado',
    status_funil: 'declinado',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'instagram',
    utm_medium: 'social',
    utm_campaign: 'remarketing_q1',
    utm_content: 'banner_desconto_30',
    utm_anuncio: 'AD-BD30-011',
    utm_posicionamento: 'stories',
  },
  {
    id: 'l41',
    nome: 'Caio Fernandez',
    telefone: '(51) 59876-5432',
    email: 'caio@micro.com',
    observacao: 'Microempresa. Nao tem fit com o produto.',
    data_criacao: '2024-02-20',
    reuniao_agendada: false,
    temperatura: 'desqualificado',
    status_funil: 'declinado',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'banner_desconto_30',
    utm_anuncio: 'AD-BD30-012',
    utm_posicionamento: 'feed',
  },
  {
    id: 'l42',
    nome: 'Nayara Braga',
    telefone: '(61) 58765-4321',
    email: 'nayara@artesanato.com',
    observacao: 'Negocio muito pequeno. Sem fit.',
    data_criacao: '2024-02-22',
    reuniao_agendada: false,
    temperatura: 'desqualificado',
    status_funil: 'declinado',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'instagram',
    utm_medium: 'social',
    utm_campaign: 'remarketing_q1',
    utm_content: 'banner_desconto_30',
    utm_anuncio: 'AD-BD30-013',
    utm_posicionamento: 'feed',
  },
  {
    id: 'l43',
    nome: 'Hugo Barreto',
    telefone: '(71) 57654-3210',
    email: 'hugo@startup2.com',
    observacao: 'Sem orcamento. Pre-revenue.',
    data_criacao: '2024-03-01',
    reuniao_agendada: false,
    temperatura: 'desqualificado',
    status_funil: 'declinado',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'google',
    utm_medium: 'cpc',
    utm_campaign: 'search_marca_q1',
    utm_content: 'carrossel_beneficios',
    utm_anuncio: 'AD-CB-009',
    utm_posicionamento: 'pesquisa',
  },
  {
    id: 'l44',
    nome: 'Viviane Pires',
    telefone: '(81) 56543-2109',
    email: 'viviane@ong.org',
    observacao: 'ONG sem recursos. Nao e cliente ideal.',
    data_criacao: '2024-03-05',
    reuniao_agendada: false,
    temperatura: 'desqualificado',
    status_funil: 'declinado',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'video_depoimento_cliente',
    utm_anuncio: 'AD-VDC-010',
    utm_posicionamento: 'feed',
  },
  // Mais alguns em varias etapas para melhorar metricas
  {
    id: 'l45',
    nome: 'Rogerio Cunha',
    telefone: '(11) 55432-1098',
    email: 'rogerio@mineracao.com',
    observacao: 'Grande empresa. Muito interesse.',
    data_criacao: '2024-03-28',
    data_reuniao: '2024-04-05',
    hora_reuniao: '09:00',
    link_meet: 'https://meet.google.com/rog-mine-ral',
    reuniao_agendada: true,
    temperatura: 'quente',
    status_funil: 'agendado',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'linkedin',
    utm_medium: 'social',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'carrossel_beneficios',
    utm_anuncio: 'AD-CB-010',
    utm_posicionamento: 'feed',
  },
  {
    id: 'l46',
    nome: 'Adriana Lima',
    telefone: '(21) 54321-0987',
    email: 'adriana@exportacao.com',
    observacao: 'Empresa exportadora. Agendado.',
    data_criacao: '2024-03-29',
    data_reuniao: '2024-04-06',
    hora_reuniao: '15:00',
    link_meet: 'https://meet.google.com/adri-expo-rt',
    reuniao_agendada: true,
    temperatura: 'muito_quente',
    status_funil: 'agendado',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'video_depoimento_cliente',
    utm_anuncio: 'AD-VDC-011',
    utm_posicionamento: 'feed',
  },
  {
    id: 'l47',
    nome: 'Nelson Teixeira',
    telefone: '(31) 53210-9876',
    email: 'nelson@transporte.com',
    observacao: 'Empresa de transporte. Follow-up enviado.',
    data_criacao: '2024-03-26',
    reuniao_agendada: false,
    temperatura: 'morno',
    status_funil: 'followup2',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'youtube',
    utm_medium: 'video',
    utm_campaign: 'brand_awareness_q1',
    utm_content: 'reels_duvidas_frequentes',
    utm_anuncio: 'AD-RDF-006',
    utm_posicionamento: 'in_stream',
  },
  {
    id: 'l48',
    nome: 'Elisa Correia',
    telefone: '(41) 52109-8765',
    email: 'elisa@design.com',
    observacao: 'Studio de design. Respondeu positivo.',
    data_criacao: '2024-03-27',
    reuniao_agendada: false,
    temperatura: 'morno',
    status_funil: 'followup1',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'instagram',
    utm_medium: 'social',
    utm_campaign: 'remarketing_q1',
    utm_content: 'video_resultado_antes_depois',
    utm_anuncio: 'AD-VRAD-008',
    utm_posicionamento: 'reels',
  },
  {
    id: 'l49',
    nome: 'Walter Soares',
    telefone: '(51) 51098-7654',
    email: 'walter@rural.com',
    observacao: 'Agronegocio. Entrou via Google.',
    data_criacao: '2024-04-04',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'trafego_pago',
    vendedor_id: 'u2',
    sdr_id: 'u4',
    utm_source: 'google',
    utm_medium: 'cpc',
    utm_campaign: 'search_marca_q1',
    utm_content: 'carrossel_beneficios',
    utm_anuncio: 'AD-CB-011',
    utm_posicionamento: 'pesquisa',
  },
  {
    id: 'l50',
    nome: 'Fatima Barros',
    telefone: '(61) 50987-6543',
    email: 'fatima@turismo.com',
    observacao: 'Agencia de turismo.',
    data_criacao: '2024-04-05',
    reuniao_agendada: false,
    temperatura: 'frio',
    status_funil: 'trafego_pago',
    vendedor_id: 'u3',
    sdr_id: 'u5',
    utm_source: 'facebook',
    utm_medium: 'cpc',
    utm_campaign: 'lancamento_produto_q1',
    utm_content: 'carrossel_beneficios',
    utm_anuncio: 'AD-CB-012',
    utm_posicionamento: 'feed',
  },
]

export const MOCK_ANOTACOES: Anotacao[] = [
  {
    id: 'a1',
    lead_id: 'l1',
    usuario_id: 'u4',
    texto: 'Rafael demonstrou muito interesse no plano anual. Ele ja usa um concorrente mas esta insatisfeito com o suporte.',
    created_at: '2024-03-02T10:30:00',
  },
  {
    id: 'a2',
    lead_id: 'l1',
    usuario_id: 'u2',
    texto: 'Reuniao excelente. Falamos por 45 min. Ele quer fechar mas precisa de NF. Enviei proposta por email.',
    created_at: '2024-03-05T11:00:00',
  },
  {
    id: 'a3',
    lead_id: 'l1',
    usuario_id: 'u2',
    texto: 'Contrato assinado! Rafael confirmou pagamento via boleto para dia 10.',
    created_at: '2024-03-06T14:00:00',
  },
  {
    id: 'a4',
    lead_id: 'l2',
    usuario_id: 'u5',
    texto: 'Beatriz pediu uma demonstracao do produto antes da reuniao. Enviei o link do tour guiado.',
    created_at: '2024-03-04T09:00:00',
  },
  {
    id: 'a5',
    lead_id: 'l2',
    usuario_id: 'u3',
    texto: 'Demo excelente. Ela ja tem budget aprovado para Q1. Negocio pratico.',
    created_at: '2024-03-08T15:00:00',
  },
  {
    id: 'a6',
    lead_id: 'l14',
    usuario_id: 'u5',
    texto: 'Leticia e CFO de fintech. Equipe de 8 vendedores. Alto potencial.',
    created_at: '2024-03-26T10:00:00',
  },
  {
    id: 'a7',
    lead_id: 'l15',
    usuario_id: 'u4',
    texto: 'Bruno viu o video no YouTube e clicou direto. Muito engajado na conversa inicial.',
    created_at: '2024-03-27T09:00:00',
  },
  {
    id: 'a8',
    lead_id: 'l11',
    usuario_id: 'u2',
    texto: 'Reuniao realizada. Thiago gostou da proposta mas quer consultar socio. Follow-up em 2 dias.',
    created_at: '2024-03-25T11:00:00',
  },
]

export const MOCK_HISTORICO: HistoricoMovimentacao[] = [
  {
    id: 'h1',
    lead_id: 'l1',
    de_status: null,
    para_status: 'trafego_pago',
    usuario_id: 'u1',
    data: '2024-03-01T08:00:00',
    observacao: 'Lead cadastrado automaticamente via webhook',
  },
  {
    id: 'h2',
    lead_id: 'l1',
    de_status: 'trafego_pago',
    para_status: 'primeiro_contato',
    usuario_id: 'u4',
    data: '2024-03-01T10:00:00',
  },
  {
    id: 'h3',
    lead_id: 'l1',
    de_status: 'primeiro_contato',
    para_status: 'agendado',
    usuario_id: 'u4',
    data: '2024-03-02T14:00:00',
    observacao: 'Reuniao agendada para 05/03 as 10h',
  },
  {
    id: 'h4',
    lead_id: 'l1',
    de_status: 'agendado',
    para_status: 'reuniao_realizada',
    usuario_id: 'u2',
    data: '2024-03-05T11:00:00',
  },
  {
    id: 'h5',
    lead_id: 'l1',
    de_status: 'reuniao_realizada',
    para_status: 'contrato_enviado',
    usuario_id: 'u2',
    data: '2024-03-05T14:00:00',
  },
  {
    id: 'h6',
    lead_id: 'l1',
    de_status: 'contrato_enviado',
    para_status: 'contrato_assinado',
    usuario_id: 'u2',
    data: '2024-03-06T09:00:00',
  },
  {
    id: 'h7',
    lead_id: 'l1',
    de_status: 'contrato_assinado',
    para_status: 'fechado',
    usuario_id: 'u2',
    data: '2024-03-07T10:00:00',
    observacao: 'Pagamento confirmado',
  },
]

export const CREDENTIALS = [
  { email: 'admin@correpool.com', senha: '123456', userId: 'u1' },
  { email: 'carlos@correpool.com', senha: '123456', userId: 'u2' },
  { email: 'ana@correpool.com', senha: '123456', userId: 'u3' },
  { email: 'pedro@correpool.com', senha: '123456', userId: 'u4' },
  { email: 'mariana@correpool.com', senha: '123456', userId: 'u5' },
]
